import type { Metadata } from 'next';
import '@radix-ui/themes/styles.css';
import './theme.config.css';
import './globals.css';
import NavBar from './NavBar';
import { Container, Theme, ThemePanel } from '@radix-ui/themes';
import { Inter } from 'next/font/google';
import AuthProvider from './auth/Provider';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable}  h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <AuthProvider>
          <Theme accentColor="violet">
            <NavBar />
            <main className="p-5">
              <Container>{children}</Container>
            </main>
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
